services: docker

env:
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: xenial
  - distribution: debian
    version: stretch
  - distribution: debian
    version: jessie

sudo: required

language: python

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/${distribution}-${version}.dockerfile --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/testing_role:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/testing_role/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/testing_role/tests/test.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'
